# Generated by Django 2.0.5 on 2018-05-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('node', models.CharField(max_length=100)),
                ('lol', models.CharField(max_length=100)),
            ],
        ),
    ]
